spring:
  datasource:
    initialization-mode: always
    username: viru@virendrams2014gmail.onmicrosoft.com
    url: jdbc:postgresql://cml-postgress-db.postgres.database.azure.com:5432/testdb
    platform: postgres
    #password: s$cret
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: none