spring:
  datasource:
    jdbc-url: jdbc:postgresql://cml-postgress-db.postgres.database.azure.com:5432/testdb
    username: viru@virendrams2014gmail.onmicrosoft.com
    #password: my_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect