
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://cml-postgress-db.postgres.database.azure.com:5432/testdb
    username: viru@virendrams2014gmail.onmicrosoft.com
    driverClassName: org.postgresql.Driver